name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: asitos
          template: classic
          base: header, activity, community, repositories, metadata

          # 🧩 plugins start here
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 5

          plugin_stargazers: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          config_timezone: India
