name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: asitos
          template: classic

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent          # shows recently played instead of currently playing (less likely to be blank)
          plugin_music_limit: 1
          plugin_music_time_range: short    # only fetch recent tracks
          config_timezone: Asia/Kolkata
