name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: asitos
          template: classic
          base: header, activity, community, repositories, metadata

          # 🧩 plugins start here
          config_timezone: Asia/Kolkata
          plugin_leetcode: yes
          plugin_leetcode_user: asitos
          plugin_leetcode_sections: solved  
          plugin_leetcode_country: global
          output: github-metrics.svg



